const pageText = {
    hk: {
        home: "主頁",
        about: "關於我們",
        services: "服務",
        vouchers: "長者社區照顧服務券",
        info: "資訊",
        stroke: "中風",
        parkinson: "帕金森",
        contactUs: "聯絡我們",
        blog: "文章",
        bookNow: "立即預約",
        search: "搜尋",
        emailUs: "電郵",
        callUs: "電話",
        slogan:"Beauty Is A State Of Mind",
        ourBeautyServices:"我們的美容服務",
        ourBeautyServicesDescription:"我們提供一系列的美容服務，包括臉部護理、身體護理、美甲、美髮等等。我們的專業美容師會根據您的需要，為您提供最合適的服務。",
        eyebrow:"眉形設計",
        eyebrowDescription:"我們的專業美容師會根據您的面部特徵，為您設計最適合的眉形。",
        viewMore:"查看更多",
        eyelashes:"睫毛護理",
        eyelashesDescription:"我們的美容師會根據您的需要，為您提供最合適的睫毛護理。",
        mesotherapy:"美塑療程",
        mesotherapyDescription:"我們的美容師會根據您的需要，為您提供最合適的美塑療程。",
        lips:"唇部護理",
        lipsDescription:"我們的美容師會根據您的需要，為您提供最合適的唇部護理。",
        viewAllServices:"查看所有服務",
        knowMoreAboutUs:"關於我們",
        knowMoreAboutUsDescription:"我們是一間專業的美容院，提供一系列的美容服務，包括臉部護理、身體護理、美甲、美髮等等。我們的專業美容師會根據您的需要，為您提供最合適的服務。",
        awardWinning:"獲獎",
        awardWinningDescription:"我們的美容院曾獲得多個獎項，包括最佳美容院、最佳美容師等等。",
        experience:"10年+經驗",
        experienceDescription:"我們的美容師擁有10年以上的經驗，為您提供最專業的服務。",
        reliableProvider:"可靠的產品提供商",
        reliableProviderDescription:"我們的美容院提供最優質的產品，為您提供最優質的服務。",
        newEyebrowPlan:"新眉形設計",
        newEyebrowPlanDescription1:"眉毛決定一個人的氣色好壞，在妝容完整度上佔有一席之地，不過對天生沒有眉毛、毛流雜亂、沒有眉型、不會修眉對畫眉毛也苦手的人來說，要勾勒出適合的眉毛並非易事，幸好現在霧眉、飄眉技術已臻純熟，不僅可以修飾眉型，還能配合喜好客製化調整，成為無眉星人和手殘黨的一大救星！",
        newEyebrowPlanDescription2:"我們提供多種不同的眉形設計，讓您選擇最適合您的眉形。",
        bookNow:"立即預約",
        getAppointment:"預約",
        getSpecialDiscount:"現在預約，即可享有特別優惠！",
        ourTeam:"我們的團隊",
        ourTeamDescription:"我們的團隊由一群專業的美容師組成，為您提供最專業的服務。",
        chiefBeautician:"首席美容師",
        assistantBeautician:"助理美容師",
        beautician:"美容師",
        viewAllTeam:"查看所有團隊",
        clientReviews:"客戶評價",
        review1:"我非常滿意這次的服務，美容師非常專業，服務態度也很好。",
        review2:"我在這裡做了一次美容，效果非常好，我會推薦給我的朋友。",
        review3:"我非常滿意這次的服務，我會再次光顧。",
        review4:"這裡的環境非常好，美容師非常專業，我會再次光顧。",
        review5:"美容儀器非常先進，效果非常好，我會推薦給我的朋友。",
        ourPopularTreatments:"我們的熱門療程",
        ourPopularTreatmentsDescription:"我們提供多種不同的療程，包括臉部護理、身體護理、美甲、美髮等等。我們的專業美容師會根據您的需要，為您提供最合適的療程。",
        eyeBrowTreatment:"霧眉療程",
        lipsTreatment:"唇部紋繡",
        eyeLashesTreatment:"美睫療程",
        watchHowWeWork:"觀看我們的工作",
        contactInfo:"聯絡資訊",
        addressDetails:"尖沙咀金馬倫道40號金龍中心10樓1005室",
        email:"電郵",
        phone:"電話",
        whatsapp:"WhatsApp",
        openingHours:"營業時間",
        saturday:"星期六",
        sunday:"星期日",
        monday:"星期一",
        tuesday:"星期二",
        wednesday:"星期三",
        thursday:"星期四",
        friday:"星期五",



        







    },
    en: {
        home: "Home",
        about: "About Us",
        services: "Services",
        vouchers: "Voucher",
        info: "Information",
        stroke: "Stroke",
        parkinson: "Parkinson",
        contactUs: "Contact Us",
        blog: "Blog",
        bookNow: "Book Now",
        search: "Search",
        emailUs: "Email",
        callUs: "Call",
        slogan:"Beauty Is A State Of Mind",
        ourBeautyServices:"Our Beauty Services",
        ourBeautyServicesDescription:"We offer a range of beauty services, including facial care, body care, manicure, hair care, etc. Our professional beauticians will provide you with the most suitable service according to your needs.",
        eyebrow:"Eyebrow Design",
        eyebrowDescription:"Our professional beauticians will design the most suitable eyebrow shape for you according to your facial features.",
        viewMore:"View More",
        eyelashes:"Eyelash Care",
        eyelashesDescription:"Our beauticians will provide you with the most suitable eyelash care according to your needs.",
        mesotherapy:"Mesotherapy",
        mesotherapyDescription:"Our beauticians will provide you with the most suitable mesotherapy according to your needs.",
        lips:"Lip Care",
        lipsDescription:"Our beauticians will provide you with the most suitable lip care according to your needs.",
        viewAllServices:"View All Services",
        knowMoreAboutUs:"About Us",
        knowMoreAboutUsDescription:"We are a professional beauty salon, offering a range of beauty services, including facial care, body care, manicure, hair care, etc. Our professional beauticians will provide you with the most suitable service according to your needs.",
        awardWinning:"Award Winning",
        awardWinningDescription:"Our beauty salon has won multiple awards, including Best Beauty Salon, Best Beautician, etc.",
        experience:"10+ Years Experience",
        experienceDescription:"Our beauticians have over 10 years of experience, providing you with the most professional service.",
        reliableProvider:"Reliable Product Provider",
        reliableProviderDescription:"Our beauty salon provides the highest quality products to provide you with the highest quality service.",
        newEyebrowPlan:"New Eyebrow Design",
        newEyebrowPlanDescription1:"Eyebrows determine a person's complexion, occupy a place in the completeness of makeup, but for those who are naturally without eyebrows, messy hair flow, no eyebrow shape, and do not know how to draw eyebrows, it is not easy to outline suitable eyebrows. Fortunately, the technology of mist eyebrows and floating eyebrows is now very mature, not only can modify the eyebrow shape, but also can be customized according to preferences, becoming a great savior for eyebrowless stars and hand-disabled parties!",
        newEyebrowPlanDescription2:"We offer a variety of eyebrow designs for you to choose the most suitable eyebrow shape for you.",
        bookNow:"Book Now",
        getAppointment:"Appointment",
        getSpecialDiscount:"Book now and enjoy special discounts!",
        ourTeam:"Our Team",
        ourTeamDescription:"Our team is composed of a group of professional beauticians who provide you with the most professional service.",
        chiefBeautician:"Chief Beautician",
        assistantBeautician:"Assistant Beautician",
        viewAllTeam:"View All Team",
        clientReviews:"Client Reviews",
        review1:"I am very satisfied with the service this time. The beautician is very professional and the service attitude is very good.",
        review2:"I did a beauty treatment here, the effect is very good, I will recommend it to my friends.",
        review3:"I am very satisfied with the service this time, I will visit again.",
        review4:"The environment here is very good, the beautician is very professional, I will visit again.",
        review5:"The beauty equipment is very advanced, the effect is very good, I will recommend it to my friends.",
        ourPopularTreatments:"Our Popular Treatments",
        ourPopularTreatmentsDescription:"We offer a variety of treatments, including facial care, body care, manicure, hair care, etc. Our professional beauticians will provide you with the most suitable treatment according to your needs.",
        eyeBrowTreatment:"Mist Eyebrow Treatment",
        lipsTreatment:"Lip Embroidery",
        eyeLashesTreatment:"Eyelash Treatment",
        watchHowWeWork:"Watch How We Work",
        contactInfo:"Contact Information",
        addressDetails:"Room 1005, 10/F, Golden Dragon Centre, 40 Cameron Road, Tsim Sha Tsui",
        email:"Email",
        phone:"Phone",
        whatsapp:"WhatsApp",
        openingHours:"Opening Hours",
        saturday:"Saturday",
        sunday:"Sunday",
        monday:"Monday",
        tuesday:"Tuesday",
        wednesday:"Wednesday",
        thursday:"Thursday",
        friday:"Friday",


       






    }

}

module.exports = { pageText }